# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20161023_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img1',
            field=models.ImageField(upload_to='/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img2',
            field=models.ImageField(upload_to='/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img3',
            field=models.ImageField(upload_to='/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img4',
            field=models.ImageField(upload_to='/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img5',
            field=models.ImageField(upload_to='/'),
        ),
    ]
