# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20161023_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('direcccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('responsable', models.CharField(max_length=40)),
                ('cordenadas', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='img1',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img2',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img3',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img4',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img5',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
