# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20161024_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='logo',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
