# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_establecimiento_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='cordenadas',
            field=models.TextField(),
        ),
    ]
