# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_establecimiento_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='categoria',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
